### PR TITLE
update platform with working OTA and secrets

### PR DESCRIPTION
**Pull request by tony-fav**
This updates the platformio environment to function with the port and authentication required.

secrets.ini file added to store device ip and ota password.

### CODE REVIEW

**Comment by PaulWieland** [comment]
Is this entirely for OTA from platform.io?

I might have to scrap OTA support in order to have enough storage space for the code dictionary needed to support 45 series boards...

**Comment by tony-fav** [comment]
Yeah took me a little digging to find the port used by the bootstrapper you're using and make sure I had that and the OTA password included in the environment. So, I thought I'd PR it in.

Most D1 mini's nowadays are the clones with ESP-12F's on them. Those are 4mb flash boards (d1_mini board) instead of 1mb flash (d1_mini_lite). I can't see a scenario where the bin would not OTA for the 4mb boards. Also, could probably benefit from gzip OTA.

**Comment by PaulWieland** [comment]
Right, I'm planning on targeting the 4mb boards. There is 1mb available for usable sketch. That leaves me with 3mb of usable space for pre-generated codes. Each code is 19 bytes and there are 7 code types. 

3000000 / 19 / 7 = 22,500 counters

That might seem like a lot, but the hard wired button's counter is a 32 bit integer, or 16+ million counters.

I'll accept the PR soon, but just beware that I might have to ditch OTA in the future.

**Comment by tony-fav** [comment]
Fair enough!

**Comment by stanford-scs** [comment]
> Right, I'm planning on targeting the 4mb boards. There is 1mb available for usable sketch. That leaves me with 3mb of usable space for pre-generated codes. Each code is 19 bytes and there are 7 code types.
> 
> 3000000 / 19 / 7 = 22,500 counters
> 
> That might seem like a lot, but the hard wired button's counter is a 32 bit integer, or 16+ million counters.

Why do you need to pre-generate codes, rather than generating them on the fly?  Also, where do you even do this in the source code?  It looks to me like `getRollingCode` just calls `encode_wireline` each time you need a code.

**Comment by PaulWieland** [comment]
A lot has changed since then. An early alpha of version 2.0 used pre a compiled database of codes. Now they are generated dynamically.

**Pull request closed without merging**
